# Generated by Django 5.1.1 on 2025-01-26 12:18

import django.db.models.deletion
import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='reported_by',
            field=models.ForeignKey(default=incidents.models.Incidents.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='incidents.user'),
        ),
    ]
