# Generated by Django 5.1.1 on 2025-01-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reports',
        ),
        migrations.AddField(
            model_name='incident',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='incident_files/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incidentType',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Theft', 'Theft'), ('Accident', 'Accident'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.FloatField(choices=[(0.2, 'Low'), (0.6, 'Medium'), (0.8, 'High')], default='None'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
