# Generated by Django 5.1.5 on 2025-01-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.JSONField(default='None', max_length=255),
        ),
    ]
