# Generated by Django 5.1.5 on 2025-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_response',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_message',
            field=models.TextField(default='None'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
