# Generated by Django 5.1.5 on 2025-01-31 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_rename_created_at_conversation_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
