# Generated by Django 5.1.5 on 2025-01-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidents_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='remarks',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='incidents',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed')], default='Submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='incidents',
            name='true_or_false',
            field=models.BooleanField(default=False),
        ),
    ]
