# Generated by Django 5.1.1 on 2025-01-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incident_incident_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='title',
        ),
    ]
