# Generated by Django 5.1.5 on 2025-01-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_conversation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user_id',
            new_name='user',
        ),
    ]
