# Generated by Django 5.1.5 on 2025-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_rename_user_id_conversation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('Resolved', 'Resolved')], default='submitted', max_length=50),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
