# Generated by Django 5.1.1 on 2025-01-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incident_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.FloatField(choices=[(0.2, 'Low'), (0.6, 'Medium'), (0.8, 'High')], default='Low'),
        ),
    ]
