# Generated by Django 5.1.1 on 2025-01-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incident_location_alter_incident_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.FloatField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='Low'),
        ),
    ]
