# Generated by Django 5.1.5 on 2025-01-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incident_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policestations',
            name='number',
            field=models.IntegerField(),
        ),
    ]
