# Generated by Django 5.1.5 on 2025-02-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incidents_status_delete_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incidentType',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Theft', 'Theft'), ('Accident', 'Accident'), ('Injury', 'Injury'), ('Missing Persons', 'Missing Persons'), ('Natural Disaster', 'Natural Disaster'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under investigation', 'Under Investigation'), ('resolved', 'Resolved')], default='submitted', max_length=50),
        ),
    ]
