# Generated by Django 5.1.5 on 2025-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_policestations_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterreliefstations',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='firestations',
            name='number',
            field=models.IntegerField(),
        ),
    ]
