# Generated by Django 5.1.5 on 2025-02-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_incidents_incidenttype_alter_incidents_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='fire_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.firestations'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='hospital_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.hospital'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.policestations'),
        ),
    ]
