# Generated by Django 5.1.5 on 2025-02-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incidents_fire_station_incidents_hospital_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='maps_link',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='incidents',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
