# Generated by Django 5.1.5 on 2025-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_incidents_maps_link_incidents_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
