# Generated by Django 5.1.5 on 2025-02-08 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incidents_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
