# Generated by Django 5.1.5 on 2025-02-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_incidents_count_alter_incidents_reported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incidentType',
            field=models.CharField(choices=[('Domestic Violence', 'Domestic Violence'), ('Child Abuse', 'Child Abuse'), ('Sexual Harassment', 'Sexual Harassment'), ('Stalking', 'Stalking'), ('Human Trafficking', 'Human Trafficking'), ('Fire', 'Fire'), ('Theft', 'Theft'), ('Accident', 'Accident'), ('Injury', 'Injury'), ('Missing Persons', 'Missing Persons'), ('Natural Disaster', 'Natural Disaster'), ('Medical Emergency', 'Medical Emergency'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='true_or_false',
            field=models.BooleanField(default=True),
        ),
    ]
